### ISSUE TITLE
Missing punctuations

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#13]
Super minor issue, but.. enh... consistency.
Missing "。"

![image](https://user-images.githubusercontent.com/5353151/33640881-383108fc-da87-11e7-94c4-8478d59f5bb7.png)

**Comment by DJTB** [comment]
As well as
![image](https://user-images.githubusercontent.com/5353151/33695355-18fd3508-db51-11e7-9214-f86f770dff8d.png)

**Comment by DJTB** [comment]
トムの友達ともだちって、会あったことあったっけ。
Was it (that you said) that you had met Tom's friend?

。 --> ？

**Comment by TheGreatestZenMaster** [comment]
Fixed!
