### ISSUE TITLE
Future improvement

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#14]
Once all the grammar is done, it would be good (though time-consuming) to go through every grammar point and add some extra tags (similar to 硬い stiff).

The main ones I'm thinking of are _written_ and _spoken_. 
For example 一方で is mainly in written contexts I believe.

I have a tendency to try to use grammar that is mainly used in writing when speaking, which is of course weird. Seeing an icon every time would really help drive the point home.

Another set of tags (only where necessary) might be _formal_ and _casual_. 
Like なんか・なんて・なんと wouldn't really be used in a formal setting.

I expect the quickest way would probably be to get a native speaker to go through a list of the grammar points.

**Comment by TheGreatestZenMaster** [comment]
That is a good idea. I think the written and spoken tags would be very beneficial. Are you thinking adding it to the review page would be best? (I am guessing that is what you mean by see it every time?)

**Comment by DJTB** [comment]
Wherever it can be reinforced regularly, reviews and individual grammar page I guess.
I can't recall if the 硬い tag appears in the review page, but I would suppose you would keep it consistent with other tags.

**Comment by DJTB** [comment]
Ok so it seems that the 硬い tag isn't in the quiz (or I just didn't notice it) since I misinterpreted one of these a moment ago.

![image](https://user-images.githubusercontent.com/5353151/33918745-412215be-e009-11e7-9d0b-1668e7a68b69.png)

I'd reach for で if asked the second question, and にとって for the third question normally.
But! If the tag was visible in the quiz, I'd know to think of a more stiff expression to answer with.

**Comment by TheGreatestZenMaster** [comment]
That would help quite a bit I think! We will look to add it.
