### ISSUE TITLE
直す sentence

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#16]
水に見えるけど、見直したらウォッカと分かる。
It looks like water **but,** if you look again, you will **realized** that it is vodka.
It looks like water, but if you look again you will realize it is vodka.

Although Japanese does it due to the placement of けど, English won't put a comma after "but" unless it is directly followed by another interjection - like "but, of course, you will realize..."

**Comment by DJTB** [comment]
This occurs in both the quiz and the examples*

**Comment by TheGreatestZenMaster** [comment]
Fixed.
