### ISSUE TITLE
につれて question

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#20]
こっちらの木が大きくなるにつれて、影が広がる。
As these trees grow tall, their shade spreads.

Is こっちら a typo deciding between こっち・こちら, or intentional?
I did some research, but it was inconclusive and I remain unsure! :stuck_out_tongue_closed_eyes:

**Comment by TheGreatestZenMaster** [comment]
You are correct, that should be こちら.
