### ISSUE TITLE
っぱなし meaning

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#21]
This seems too narrow a description by the inclusion of the word "on".  

![image](https://user-images.githubusercontent.com/5353151/33695035-43ab520a-db4f-11e7-9763-af6945734bd0.png)

Perhaps changing it along the lines of "leaving something in a state, left as it is"?

**Comment by TheGreatestZenMaster** [comment]
I changed the wording. It was too narrow of a description.
