### ISSUE TITLE
ないことはない structure

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#23]
![image](https://user-images.githubusercontent.com/5353151/33791275-7f441cd6-dcdd-11e7-9cc7-8edf97334c37.png)

Shouldn't the third listing be: Noun・ではない + ことはない to make a double negative?
Or am I misunderstanding something crucial here :laughing: ?

**Comment by TheGreatestZenMaster** [comment]
That was a pretty big part of the grammar to forget. :laughing:
