### ISSUE TITLE
ぶりに sentences

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#26]
I meet a high school friend who I hadn't seen for 10 years.
I **met** a high school friend who I hadn't seen for 10 years.

It was the first time since the fall three years ago that I saw a view this beautiful.
**This is** the first time since <s>the</s> fall three years ago that **I've seen** a view this beautiful.

**Comment by TheGreatestZenMaster** [comment]
Fixed!
