### ISSUE TITLE
だけあって alternate grammar

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#28]
だけに should be acceptable for all the だけあって questions.

The reverse might not necessarily be true if there are negative direction だけに sentences added.
But I think it should always be safe to substitute だけに in for だけあって.

**Comment by TheGreatestZenMaster** [comment]
We checked and だけあって won't work for any of the だけに sentences, but だけに will work with the だけあって sentences we have. I have updated them to reflect that.
