### ISSUE TITLE
Text encoding

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#3]
What text editor are you using? 
What system language?

Because you're getting missing character encoding in committed files.
`b-N4.rb` line 1474
```
atode.study_questions.create!(japanese: "���事���し�����くじ）<span class='study-area-input'>____</span>、お皿（さら）を洗（あら）わなくてはいけない。",
                               answer: "のあとで",
                               english: "I have to wash dishes <strong>after</strong> a meal.")

atode.study_questions.create!(japanese: "また<span class='study-area-input'>____</span>、会（あ）いましょう。",
                               answer: "������で",
                               english: "Let's meet <strong>later</strong>.")   
```

**Comment by TheGreatestZenMaster** [comment]
I am using Cloud 9 and it uses UFT-8 encoding. I tried to look into why all those dropped characters are happening but I couldn't find anything concrete. Seems like it is the way that the file is saved and opened that is causing it.

**Comment by TheGreatestZenMaster** [comment]
It is a pain but those seed files were mostly just to populate the database and we only use them as references now.

**Comment by DJTB** [comment]
Ah, I assume there's not point in me directly adding to them then for something like #4. You need to modify the production DB directly yeah?

**Comment by TheGreatestZenMaster** [comment]
You are welcome to change them directly, but if it easier for you to just list them off then just do that. It isn't much more work for me to change the sentence in the code while I am updating the DB.

**Comment by DJTB** [comment]
I'll just make issues for anything I come across then and let you modify it. Easier to keep track of them without double handling.

**Comment by TheGreatestZenMaster** [comment]
Perfect! Thanks!

**Comment by DJTB** [comment]
No idea how cloud9 works, but you might be able to run all the files there through a flavor of `iconv` to get the encoding set correctly. 50/50 shot.
