### ISSUE TITLE
だけあって quiz question

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#30]
Being the case that that actor is carful about his posture, the way he walks is beautiful.
Being the case that that actor is **careful** about his posture, the way he walks is beautiful.

This is also a good opportunity to use an alternate English translation since the appearance of  "that that" is fairly clunky. Maybe something like: "That actor is always careful about his posture and as you'd expect, the way he walks is beautiful."

Not sure if intentional, but this quiz question isn't in the examples by the way*

**Comment by TheGreatestZenMaster** [comment]
Changed the sentences to match.
