### ISSUE TITLE
ごとに たびに alternate grammar

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#32]
Recently answered (N)ごとに incorrectly for (N)のたびに, though they are pretty much* interchangeable.

For the examples listed (Noun / Verb + grammar) these should both be accepted answers for the other grammar point's quiz questions.

*If any quantity questions are ever added to ごとに (currently there are none), たびに shouldn't be allowed in place of ごとに (but おきに could) though.

**Comment by TheGreatestZenMaster** [comment]
Fixed!
