### ISSUE TITLE
とquiz question

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#33]
![image](https://user-images.githubusercontent.com/5353151/34079061-b3157e90-e379-11e7-86c8-1ecd36f3fe3f.png)

Correct answer was  "といいました". 

Not a huge deal since users can ignore their answer, but should probably add [casual] / [formal] to this. Or accept multiple answers (といった・といいました・っていった・っていいました)

**Comment by DJTB** [comment]
Actually, I just noticed that the って question *includes the verb*.  
![image](https://user-images.githubusercontent.com/5353151/34085012-d166a9fa-e3dd-11e7-9c7d-6a862c49914c.png)

Maybe that's what should be happening here, since the grammar point is just と by itself.

**Comment by TheGreatestZenMaster** [comment]
Fixed them!
