### ISSUE TITLE
つもりで confusion

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#34]
![image](https://user-images.githubusercontent.com/5353151/34136435-e2afe46a-e4b9-11e7-9f91-bd87e460df58.png)

The た is highlighted, though the examples include a non-た form.
Is it because the verb *after* つもりで is in -た form?

![image](https://user-images.githubusercontent.com/5353151/34136467-1c28d116-e4ba-11e7-98b9-9f1e2f385acf.png)

Doing some collocation searches showed つもりで used after all sorts of conjugations.

Not saying the (た) in the structure is wrong, I'm just not clear as to the proper usage :)

**Comment by TheGreatestZenMaster** [comment]
Fixed.
