### ISSUE TITLE
つもり quiz question

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#38]
English says "do not intend".
Answer only accepts "ではなかった" (not じゃない, じゃなかった etc)
Same example question shows "ではない"

![image](https://user-images.githubusercontent.com/5353151/34366608-3affe46a-eaf2-11e7-8123-70ac86f41706.png)

**Comment by DJTB** [comment]
Also, should be "intend **to**"

**Comment by TheGreatestZenMaster** [comment]
Fixed and cleaned up hint to include the do not
