### ISSUE TITLE
Alternate (accepted) answers

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#4]
Not sure how you've set up the fields for alternate accepted answers.
If you could correct さえ___ば I can look at the commit to figure it out easily for other grammar points.

The Noun form is an optional (で)さえ, but this screen looks like it's requiring で - whereas the answers won't accept で at all.

![image](https://user-images.githubusercontent.com/5353151/33467071-176540be-d6a6-11e7-9b0d-da232ba8898e.png)  

![image](https://user-images.githubusercontent.com/5353151/33467105-389b18a8-d6a6-11e7-865d-624515a37e87.png)

Proposed changes:
1) List noun form as (で)さえ (all yellow, no red highlight?)
2) add でさえ alternates for noun example questions

**Comment by TheGreatestZenMaster** [comment]
I will update it.

Alternate answers/grammar fall into two categories
alternate_answers: which is a hash that takes the answer as the key and then the hint/help as the answer like
alternate_answers: {"だ": "We are looking for the polite 'to be'"}

and alternate_grammar: which is an array and takes any grammar that works and needs to include the answer value as well in there like
alternate_grammar: ["でさえあれば", "さえあれば"] and so on.

**Comment by TheGreatestZenMaster** [comment]
Should be fixed now.
