### ISSUE TITLE
代わりに sentences

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#5]
バナナが嫌いで食べれないからビタミンが取れない。バナナの代わりに何を食べたらいい？
I don't like bananas so I don't eat them and can't get those vitamens. What should I eat in place of banana?.
I don't like bananas so I don't eat them and can't get those **vitamins**. What should I eat in place of **banana?**
(remove extra ".")

彼が遅刻をしてしまったので、彼の代わりに発表した。
Since he was running late, I presented in his stead.
Since he was running late, I presented **instead of him**.
(in his stead is somewhat archaic, clunky)

先生は風邪をひいて休んだので、代わりに校長先生が授業をした。
Because the teacher caught a cold and took the day off, the principle taught the class in his place.
Because the teacher caught a cold and took the day off, the **principal** taught the class in his place.

**Comment by TheGreatestZenMaster** [comment]
Fixed!
