### ISSUE TITLE
ことになる sentence

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#6]
明日が雨ならば、１週間降り続くことになる。
If it rains tomorow, it will end up being a week straight of rain.
If it rains **tomorrow**, it will end up being a week straight of rain.

The English in this is too forced and makes it sound like a prediction along the lines of "if it rains tomorrow, the following week will be full of rain" when really (I believe) the Japanese means "If it rains tomorrow, it will have been a week of continued rain (since it began, a week ago)". The English really needs to be "it will have been" which although is correct - it then hides/confuses the Japanese meaning of a resultant state.

The other examples are good, so maybe you could just replace this particular sentence with something straightforward?

なぜこんなことになるんだろう？
How could it end up like this?

**Comment by TheGreatestZenMaster** [comment]
Fixed the English to better reflect the meaning.
