### ISSUE TITLE
さえ＿ば sentences

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#7]
死体さえ発見できれば、警察が解決をする。
Only if the police can find the body will the solve the case.
Only if the police can find the body will **they** solve the case.

彼は自分さえ良ければ、いいと思っている。
He thinks that **it is** fine if it is only **<s>is</s>** good for him.
He thinks that it's fine **only if** it is good for him.

"only good for him" emphasises the idea that "it can only be good (not bad) for him (and no-one else)" whereas I believe the Japanese sentence is more neutral, emphasising the "only if" more.

I could be wrong and happy to be corrected, but this rewording seems to match the Japanese better.

**Comment by TheGreatestZenMaster** [comment]
You are correct. That is much clearer way of saying it!
