### ISSUE TITLE
ついでに sentences

### ISSUE THREAD

**Issue by DJTB** [TheGreatestZenMaster/japanese_grammar#9]
散歩のついでに、郵便局に寄って切手を買いました。
While <s>**I was**</s> taking walk I stopped by the post office and bought stamps.
While taking **a** walk I stopped by the post office and bought stamps.

毎日仕事から帰るついでに、コンビニでコーヒーを買う。
While coming home from work, I always get a coffe at the convenience store.
While coming home from work, I always get a **coffee** at the convenience store.

**Comment by TheGreatestZenMaster** [comment]
Thanks!
